create table if not exists text_ads (
    id bigint generated by default as identity primary key,

    title text not null,

    type text not null,

    city text not null,

    description text not null,

    telegram text,

    created_at timestamptz default now()
);